# Generated by Django 4.1.7 on 2023-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Company", models.CharField(max_length=500, null=True)),
                ("Location", models.CharField(max_length=500, null=True)),
                ("JD", models.CharField(max_length=20000, null=True)),
                ("posted", models.CharField(max_length=500, null=True)),
                ("link", models.URLField(max_length=10000, null=True)),
            ],
        ),
    ]
