# Generated by Django 4.1.7 on 2023-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0002_delete_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Company", models.TextField(max_length=500, null=True)),
                ("Location", models.TextField(max_length=500, null=True)),
                ("JD", models.TextField(max_length=20000, null=True)),
                ("posted", models.TextField(max_length=500, null=True)),
                ("link", models.TextField(max_length=10000, null=True)),
            ],
        ),
    ]
