# Generated by Django 4.1.7 on 2023-03-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
