# Generated by Django 4.1.7 on 2023-03-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
